# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-02 14:54
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20)),
                ('firstName', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('positionx', models.FloatField()),
                ('positiony', models.FloatField()),
                ('positionz', models.FloatField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('questionHistoric', models.CharField(max_length=55, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')])),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionText', models.CharField(max_length=255)),
                ('answer1', models.CharField(max_length=100)),
                ('answer2', models.CharField(max_length=100)),
                ('answer3', models.CharField(max_length=100)),
                ('answer4', models.CharField(max_length=100)),
                ('rightAnswer', models.CharField(choices=[('1', models.CharField(max_length=100)), ('2', models.CharField(max_length=100)), ('3', models.CharField(max_length=100)), ('4', models.CharField(max_length=100))], max_length=20)),
                ('difficulty', models.IntegerField()),
                ('topic', models.CharField(max_length=20)),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centrex', models.FloatField()),
                ('centrey', models.FloatField()),
                ('centrez', models.FloatField(default=0)),
                ('rayon', models.IntegerField()),
                ('questionList', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')])),
                ('startTime', models.IntegerField()),
                ('CurrentQuestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('points', models.TextField()),
            ],
        ),
    ]
