# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-03 13:32
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import re


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spot',
            old_name='CurrentQuestion',
            new_name='currentQuestion',
        ),
        migrations.AddField(
            model_name='player',
            name='account',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='firstName',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='positionx',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='player',
            name='positiony',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='player',
            name='questionHistoric',
            field=models.CharField(default='[]', max_length=55, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
